#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}


# ──────────────────────────────────────────────────────────────────────────
# STAGES: the release wizard (flyhard/simmarken#9).
#
# Walks the maintainer through phases B (Play Console) and C (pipeline) of the
# release runbook, docs/PLAY-CONSOLE-SETUP.md. The runbook's status table is
# the only state: ticked steps are skipped. Signing comes from 1Password via
# release.env (ADR-0019). Never commits or pushes.
# ──────────────────────────────────────────────────────────────────────────

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
cd "$REPO_ROOT"

RUNBOOK="docs/PLAY-CONSOLE-SETUP.md"
RELEASE_ENV="release.env"
PLAY_CONSOLE_URL="https://play.google.com/console"
SERVICE_ACCOUNT_DOCUMENT="${SERVICE_ACCOUNT_DOCUMENT:-Play service account}"
TODAY="$(date +%Y-%m-%d)"

# shellcheck source=scripts/lib/release-runbook.sh
source "$SCRIPT_DIR/lib/release-runbook.sh"

usage() {
  cat <<'EOF'
Usage: scripts/release-wizard.sh <phase>

Walks you through the remaining manual release steps on your own machine and
records the evidence in docs/PLAY-CONSOLE-SETUP.md (the release runbook).

Phases:
  play       Phase B, runbook steps 2–7: Play Console app record, store
             listing, Play App Signing, first manual upload (versionCode 1),
             service account and PLAY_SERVICE_ACCOUNT_JSON, internal testers.
  pipeline   Phase C, runbook steps 8–10: keystore secrets in GitHub, first
             automated upload through .github/workflows/release.yml, update
             installed from Play.

Phase A (go public) is already done and has no wizard.

Prerequisites (checked before anything else runs):
  both       op (1Password CLI, signed in), gh (signed in, admin on the repo),
             git, awk
  play       keytool, jarsigner (JDK 17+), Android SDK (ANDROID_HOME or
             local.properties), python3 and rsvg-convert for store graphics
  pipeline   base64; release.yml on main for step 9 (flyhard/simmarken#8)

Signing values come from the op:// references in release.env (ADR-0019).
Secrets are piped from op straight into gh; they are never printed, stored in
a shell variable, or written to disk.

Re-running is safe: steps ticked in the runbook's status table are skipped.
The wizard never commits or pushes. It ends by showing the runbook diff for
you to review and commit.

Environment:
  SERVICE_ACCOUNT_DOCUMENT   1Password document title for the Play service
                             account JSON (default: "Play service account")

Options:
  --help     Show this help and exit
EOF
}

die() { printf '%s✗ %s%s\n' "$RED" "$1" "$RESET" >&2; exit 1; }
ok()  { printf '  %s✓%s %s\n' "$GREEN" "$RESET" "$1"; }

PHASE="${1:-}"
case "$PHASE" in
  --help|-h) usage; exit 0 ;;
  play|pipeline) ;;
  "") usage >&2; exit 1 ;;
  *) echo "Unknown phase: $PHASE" >&2; usage >&2; exit 1 ;;
esac
[[ $# -le 1 ]] || { echo "Too many arguments." >&2; usage >&2; exit 1; }

# ── release.env: keystore path and 1Password references ───────────────────

# env_value KEY prints KEY's value from release.env (the reference, not the secret).
env_value() {
  local line
  line="$(grep -E "^${1}=" "$RELEASE_ENV" | tail -n1)" || die "$RELEASE_ENV has no $1 line."
  printf '%s' "${line#*=}"
}

# Keystore path with a leading ~ expanded, as the Gradle build does.
keystore_path() {
  local path
  path="$(env_value ANDROID_KEYSTORE_FILE)"
  printf '%s' "${path/#\~/$HOME}"
}

# op://Vault/Item/field → vault and item of the keystore item.
keystore_vault() { env_value KEYSTORE_PASSWORD | awk -F/ '{print $3}'; }
keystore_item()  { env_value KEYSTORE_PASSWORD | awk -F/ '{print $4}'; }

# with_signing CMD… runs CMD with the signing variables from release.env
# injected by 1Password. op masks the secret values in CMD's output.
with_signing() { op run --env-file="$RELEASE_ENV" -- "$@"; }

# ── prerequisites ─────────────────────────────────────────────────────────

MISSING=()
need() { # need CMD "install hint"
  command -v "$1" >/dev/null 2>&1 || MISSING+=("$1: $2")
}

check_prerequisites() {
  need git "install git"
  need awk "install awk"
  need op "1Password CLI: https://developer.1password.com/docs/cli/get-started/"
  need gh "GitHub CLI: https://cli.github.com (macOS: brew install gh)"
  if [[ "$PHASE" == play ]]; then
    need keytool "install JDK 17+ and put it on PATH"
    need jarsigner "install JDK 17+ and put it on PATH"
    need python3 "install Python 3.9+"
    need rsvg-convert "macOS: brew install librsvg; Debian/Ubuntu: sudo apt-get install librsvg2-bin"
    if [[ -z "${ANDROID_HOME:-}${ANDROID_SDK_ROOT:-}" ]] \
        && ! grep -q '^sdk.dir=' local.properties 2>/dev/null; then
      MISSING+=("Android SDK: install it (Android Studio) and set ANDROID_HOME or sdk.dir in local.properties")
    fi
  else
    need base64 "install coreutils"
  fi
  if ((${#MISSING[@]})); then
    printf '%sMissing prerequisites:%s\n' "$RED" "$RESET" >&2
    local m
    for m in "${MISSING[@]}"; do printf '  - %s\n' "$m" >&2; done
    exit 1
  fi

  [[ -f "$RUNBOOK" ]] || die "Run this from a checkout: $RUNBOOK not found."
  [[ -f "$RELEASE_ENV" ]] || die "$RELEASE_ENV not found (ADR-0019)."
  gh auth status >/dev/null 2>&1 || die "gh is not signed in. Run: gh auth login"
  local admin
  admin="$(gh repo view --json viewerPermission --jq .viewerPermission 2>/dev/null || true)"
  [[ "$admin" == ADMIN ]] || die "gh needs admin rights on this repository (got '${admin:-none}')."
  op whoami >/dev/null 2>&1 || die "1Password CLI is not signed in. Run: eval \"\$(op signin)\""
}

# ── shared stages ─────────────────────────────────────────────────────────

# ensure_keystore makes sure the keystore from release.env is on this machine,
# offering to download it from 1Password (ADR-0019) if it isn't.
ensure_keystore() {
  local path vault item
  path="$(keystore_path)"
  if [[ -f "$path" ]]; then
    ok "keystore found at $path"
    return
  fi
  vault="$(keystore_vault)"
  item="$(keystore_item)"
  warn "The keystore isn't on this machine yet: $path"
  confirm "Download \"$item\" from 1Password vault \"$vault\" to $path?" \
    || die "The keystore is needed to sign. Put it at $path and re-run."
  mkdir -p "$(dirname "$path")"
  chmod 700 "$(dirname "$path")"
  op document get "$item" --vault "$vault" --out-file "$path" >/dev/null
  chmod 600 "$path"
  ok "keystore downloaded to $path"
}

# record STEP EVIDENCE writes the evidence line and ticks the status row.
record() {
  runbook_set_evidence "$1" "$2" || die "Evidence for step $1 not written; fix it in $RUNBOOK by hand."
  runbook_tick "$1" "$TODAY" || die "Step $1 not ticked; tick it in $RUNBOOK by hand."
  ok "step $1 recorded in $RUNBOOK"
}

show_diff() {
  _clear
  printf '\n%s%s  Review and commit the runbook%s\n\n' "$BOLD" "$BLUE" "$RESET"
  git --no-pager diff --stat -- "$RUNBOOK" docs/prd/
  git --no-pager diff -- "$RUNBOOK"
  printf '\n'
  note "The wizard doesn't commit. When the diff looks right:"
  note "  git add $RUNBOOK && git commit -m \"Record release runbook evidence\""
}

# ── phase B: Play Console (steps 2–7) ─────────────────────────────────────

step_2() {
  stage "App record (step 2)"
  open_url "$PLAY_CONSOLE_URL"
  step "Click Create app."
  step "App name: Simmärken · Default language: Swedish – sv-SE"
  step "App or game: App · Free or paid: Free"
  step "Accept the declarations, then Create app."
  confirm "Is the app record created?" || die "Stopped at step 2. Re-run when it's done."
  record 2 "app created \`$TODAY\`"
}

step_3() {
  stage "Store listing and app content (step 3)"
  say "Generating the 512×512 icon and 1024×500 feature graphic from the launcher icon…"
  scripts/store-graphics.py generate
  ok "graphics in build/store-graphics/"
  say ""
  say "Take 2–8 phone screenshots (phone or emulator). The listing is public:"
  warn "use made-up child names only, never real ones, and no real photos."
  local dir=""
  while :; do
    ask dir "Folder with the screenshots:"
    dir="${dir/#\~/$HOME}"
    if [[ -d "$dir" ]] && scripts/store-graphics.py check-screenshots "$dir"; then
      break
    fi
    warn "Fix the screenshots above (or the folder path) and try again."
  done

  open_url "$PLAY_CONSOLE_URL"
  say "Grow users → Store presence → Main store listing (sv-SE):"
  step "Short description, e.g.: Håll koll på barnens simmärken – klarade krav och köpta märken."
  step "Full description: both catalogs, works offline, no account."
  step "Upload build/store-graphics/play-icon.png and feature-graphic.png, and the screenshots."
  pause "Press Enter when the listing is saved."
  say "Policy → App content, answering as in step 3 of $RUNBOOK:"
  step "Privacy policy: https://flyhard.github.io/simmarken/privacy-policy/"
  step "Ads: no · App access: all functionality available"
  step "Content rating (IARC): answer honestly; expect Everyone / PEGI 3"
  step "Target audience: 18+, not directed at children"
  step "Data safety: no data collected, no data shared"
  local rating=""
  ask rating "Content rating Play gave you (e.g. PEGI 3):"
  confirm "Is the data safety form submitted?" || die "Stopped at step 3. Re-run when it's done."
  record 3 "content rating = \`$rating\`, data safety submitted \`$TODAY\`"
}

# upload_key_sha256 prints the upload certificate's SHA-256 from the keystore,
# with the store password injected by 1Password.
upload_key_sha256() {
  # shellcheck disable=SC2016 # expanded by the inner shell under op run
  with_signing bash -c 'keytool -list -v -keystore "${ANDROID_KEYSTORE_FILE/#\~/$HOME}" \
      -alias "$KEY_ALIAS" -storepass:env KEYSTORE_PASSWORD' \
    | awk -F': ' '/SHA256:/{print $2; exit}'
}

normalize_fp() { printf '%s' "$1" | tr -d ' \t' | tr '[:lower:]' '[:upper:]'; }

step_4() {
  stage "Play App Signing (step 4)"
  ensure_keystore
  local local_fp console_fp tmp
  local_fp="$(upload_key_sha256)"
  [[ -n "$local_fp" ]] || die "Couldn't read the upload key's SHA-256 from the keystore."
  ok "upload key SHA-256: $local_fp"

  tmp="$(mktemp -d)"
  # The certificate is public, but keep it out of the checkout and tidy up.
  # shellcheck disable=SC2064 # expand $tmp now
  trap "rm -rf '$tmp'" EXIT
  # shellcheck disable=SC2016 # expanded by the inner shell under op run
  with_signing bash -c 'keytool -export -rfc -keystore "${ANDROID_KEYSTORE_FILE/#\~/$HOME}" \
      -alias "$KEY_ALIAS" -storepass:env KEYSTORE_PASSWORD -file "$0"' \
    "$tmp/upload_certificate.pem" >/dev/null
  ok "upload certificate exported to $tmp/upload_certificate.pem (deleted when the wizard exits)"

  open_url "$PLAY_CONSOLE_URL"
  say "Test and release → Setup → App signing:"
  step "Choose Use Google-generated app signing key (the default)."
  step "If Play asks for an upload certificate, upload $tmp/upload_certificate.pem."
  step "Then open App integrity → Upload key certificate and copy its SHA-256."
  while :; do
    ask console_fp "Paste the upload key SHA-256 shown in Play Console:"
    if [[ "$(normalize_fp "$console_fp")" == "$(normalize_fp "$local_fp")" ]]; then
      ok "fingerprints match"
      break
    fi
    warn "That doesn't match the local keystore. Check you copied the upload key, not the app signing key."
  done
  record 4 "upload-key SHA-256 matches local fingerprint, checked \`$TODAY\` (fingerprint: \`$local_fp\`)"
  rm -rf "$tmp"
  trap - EXIT
}

# internet_permissions prints how many INTERNET permissions the merged
# release manifest declares, or nothing if the manifest can't be found.
internet_permissions() {
  local manifest
  manifest="$(find app/build/intermediates -path '*release*' -name AndroidManifest.xml \
    -path '*merged_manifest*' 2>/dev/null | head -n1)"
  [[ -n "$manifest" ]] || return 0
  grep -c 'android.permission.INTERNET' "$manifest" || true
}

step_5() {
  stage "First internal-testing release (step 5)"
  local code name count
  code="$(awk '/versionCode *=/{print $3; exit}' app/build.gradle.kts)"
  name="$(awk -F'"' '/versionName *=/{print $2; exit}' app/build.gradle.kts)"
  [[ "$code" == 1 ]] || warn "versionCode is $code, not 1. The first manual upload is normally versionCode 1."
  ensure_keystore
  say "Building the signed release bundle (this takes a few minutes)…"
  with_signing ./gradlew --no-daemon bundleRelease
  scripts/verify-release-signature.sh
  count="$(internet_permissions)"
  if [[ -z "$count" ]]; then
    warn "Couldn't find the merged release manifest; check for INTERNET by hand (step 5 of $RUNBOOK)."
    confirm "Did you check it has no INTERNET permission?" || die "Stopped at step 5."
  elif [[ "$count" != 0 ]]; then
    die "The release manifest declares INTERNET. The privacy policy says the app has no network access (ADR-0003)."
  else
    ok "no INTERNET permission in the release manifest"
  fi

  open_url "$PLAY_CONSOLE_URL"
  say "Test and release → Testing → Internal testing → Create new release:"
  step "Upload app/build/outputs/bundle/release/app-release.aab"
  step "Release notes (sv-SE): Första testversionen."
  step "Save, review, and roll out to internal testing."
  confirm "Was release $code ($name) accepted on the internal track?" || die "Stopped at step 5."
  record 5 "release \`$code ($name)\` accepted on internal track \`$TODAY\`"
}

step_6() {
  stage "Service account and PLAY_SERVICE_ACCOUNT_JSON (step 6)"
  local vault json="" email
  vault="$(keystore_vault)"
  open_url "$PLAY_CONSOLE_URL"
  step "Play Console → Setup → API access → link or create a Google Cloud project."
  step "Google Cloud: enable the Google Play Android Developer API."
  step "Create a service account (e.g. play-publisher) and download a JSON key."
  step "Play Console → Users and permissions → invite its email as Release manager, for se.simmarken only."
  pause "Press Enter when the JSON key is downloaded."

  if op document get "$SERVICE_ACCOUNT_DOCUMENT" --vault "$vault" >/dev/null 2>&1; then
    ok "1Password already has \"$SERVICE_ACCOUNT_DOCUMENT\" in vault \"$vault\""
  else
    while :; do
      ask json "Path to the downloaded JSON key:"
      json="${json/#\~/$HOME}"
      [[ -f "$json" ]] && grep -q '"type": *"service_account"' "$json" && break
      warn "That isn't a service-account JSON key."
    done
    op document create "$json" --title "$SERVICE_ACCOUNT_DOCUMENT" --vault "$vault" >/dev/null
    ok "stored in 1Password as \"$SERVICE_ACCOUNT_DOCUMENT\" (vault \"$vault\")"
  fi

  op document get "$SERVICE_ACCOUNT_DOCUMENT" --vault "$vault" | gh secret set PLAY_SERVICE_ACCOUNT_JSON
  WRITTEN_SECRET+=(PLAY_SERVICE_ACCOUNT_JSON)
  ok "GitHub secret PLAY_SERVICE_ACCOUNT_JSON set"
  email="$(op document get "$SERVICE_ACCOUNT_DOCUMENT" --vault "$vault" \
    | sed -n 's/.*"client_email": *"\([^"]*\)".*/\1/p' | head -n1)"

  if [[ -n "$json" && -f "$json" ]] && confirm "Delete the local copy $json now?"; then
    rm -f "$json"
    ok "deleted $json"
  fi
  record 6 "secret created \`$TODAY\`; service-account email \`${email:-…}\`"
}

step_7() {
  stage "Internal testers (step 7)"
  open_url "$PLAY_CONSOLE_URL"
  say "Test and release → Testing → Internal testing → Testers:"
  step "Create an email list with only your own address."
  step "Copy the opt-in link, open it on your phone, and install Simmärken from Play."
  local device=""
  ask device "Device you installed it on (e.g. Pixel 8):"
  confirm "Did the app install from Play and open?" || die "Stopped at step 7."
  record 7 "installed from Play on \`$device\` \`$TODAY\`"
}

# ── phase C: pipeline (steps 8–10) ────────────────────────────────────────

# secret_from_op NAME ENV_KEY pipes the value behind ENV_KEY's op:// reference
# in release.env straight into a GitHub secret.
secret_from_op() {
  local ref
  ref="$(env_value "$2")"
  # Check the reference resolves first, so a 1Password error can't set an empty secret.
  op read "$ref" >/dev/null || die "1Password couldn't read $2 ($ref)."
  op read -n "$ref" | gh secret set "$1"
  WRITTEN_SECRET+=("$1")
  ok "GitHub secret $1 set"
}

step_8() {
  stage "Signing secrets in GitHub (step 8)"
  ensure_keystore
  say "Setting the four signing secrets from 1Password. Nothing is printed."
  base64 <"$(keystore_path)" | tr -d '\n' | gh secret set ANDROID_KEYSTORE_BASE64
  WRITTEN_SECRET+=(ANDROID_KEYSTORE_BASE64)
  ok "GitHub secret ANDROID_KEYSTORE_BASE64 set"
  secret_from_op KEYSTORE_PASSWORD KEYSTORE_PASSWORD
  secret_from_op KEY_ALIAS KEY_ALIAS
  secret_from_op KEY_PASSWORD KEY_PASSWORD
  gh secret list | grep -q '^PLAY_SERVICE_ACCOUNT_JSON' \
    || warn "PLAY_SERVICE_ACCOUNT_JSON isn't set yet; run the play phase (step 6) first."
  record 8 "secrets set \`$TODAY\`"
}

step_9() {
  stage "First automated upload (step 9)"
  gh api "repos/{owner}/{repo}/contents/.github/workflows/release.yml?ref=main" >/dev/null 2>&1 \
    || die "release.yml isn't on main yet (flyhard/simmarken#8). Re-run this phase when it's merged."
  local before run_id url code=""
  before="$(gh run list --workflow release.yml --limit 1 --json databaseId --jq '.[0].databaseId // 0')"
  gh workflow run release.yml --ref main
  say "Waiting for the run to start…"
  run_id="$before"
  local tries=0
  while [[ "$run_id" == "$before" ]]; do
    ((tries++ < 40)) || die "The dispatched run didn't show up; check https://github.com/flyhard/simmarken/actions"
    sleep 3
    run_id="$(gh run list --workflow release.yml --limit 1 --json databaseId --jq '.[0].databaseId // 0')"
  done
  url="$(gh run view "$run_id" --json url --jq .url)"
  ok "started $url"
  gh run watch "$run_id" --exit-status \
    || die "The release run failed: $url. Fix it and re-run this phase."
  ok "release run green"

  open_url "$PLAY_CONSOLE_URL"
  say "Test and release → Testing → Internal testing → Releases:"
  step "Find the new release uploaded by the workflow and note its versionCode."
  while :; do
    ask code "versionCode of the new release:"
    [[ "$code" =~ ^[0-9]+$ && "$code" -gt 1 ]] && break
    warn "The automated upload must have a versionCode above 1 (RELE-04)."
  done
  record 9 "run \`$url\` green \`$TODAY\`; \`versionCode\` \`$code\` on the internal track"
}

step_10() {
  stage "Update installed from Play (step 10)"
  say "On your phone: Play Store → Simmärken → Update."
  step "Open the app and check your existing progress is still there."
  local device=""
  ask device "Device you updated (e.g. Pixel 8):"
  confirm "Did the update install from Play with progress intact?" || die "Stopped at step 10."
  record 10 "update installed on \`$device\` \`$TODAY\`"
}

# ── run ───────────────────────────────────────────────────────────────────

check_prerequisites

if [[ "$PHASE" == play ]]; then
  FIRST=2; LAST=7; TITLE="Release wizard · Phase B: Play Console"
else
  FIRST=8; LAST=10; TITLE="Release wizard · Phase C: Pipeline"
fi

PENDING=()
while IFS= read -r s; do PENDING+=("$s"); done < <(runbook_pending "$FIRST" "$LAST")
if ((${#PENDING[@]} == 0)); then
  echo "Steps $FIRST–$LAST are all ticked in $RUNBOOK. Nothing to do."
  exit 0
fi

TOTAL_STAGES=${#PENDING[@]}
banner "$TITLE"
for s in "${PENDING[@]}"; do
  "step_$s"
done

finish
if [[ "$PHASE" == play ]]; then
  note "Phase B done: tick RELE-01, RELE-02 and RELE-05 in docs/prd/0002-release-and-open-source.md."
else
  note "Phase C done: tick CI-02, RELE-03 and RELE-04 in docs/prd/0002-release-and-open-source.md."
fi
pause "Press Enter to see the runbook diff."
show_diff
